default: &default
  acme:
    endpoint: "https://5f2be0b4ffc88500167b85a0.mockapi.io/suppliers/acme"
  patagonia:
    endpoint: "https://5f2be0b4ffc88500167b85a0.mockapi.io/suppliers/patagonia"
  paperflies:
    endpoint: "https://5f2be0b4ffc88500167b85a0.mockapi.io/suppliers/paperflies"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
